clear;
fprintf('pf =');
pf = 0.8;
disp(pf);
fprintf('theta =');
theta = atan(pf);
disp(theta);
P = 20*(10^6);
Vl = 33*(10^3);
fprintf('Vr =');
Vr = (Vl)/sqrt(3);
disp(Vr);
fprintf('Ir =');
Ir = P/(sqrt(3)*Vl*pf);
disp(Ir);
Ir = Ir*(cos(theta) + 1i*sin(theta));
z = 0.1 + (1i*0.4);
y = 1i*3*10^(-6);
l = 250;
f = 50;
w = 2*pi*f;
fprintf('Z =');
Z = z*l;
disp(Z);
fprintf('Y =');
Y = y*l;
disp(Y);
fprintf('Zc =');
zc = sqrt(z/y);
disp(zc);
fprintf('gama =');
gama = sqrt(y*z);
disp(gama);
fprintf('alpha =');
alpha = real(gama);
disp(alpha);
fprintf('beta =');
beta = imag(gama);
disp(beta);
fprintf('A =');
A = cosh(gama*l);
disp(A);
fprintf('B =');
B = zc*sinh(gama*l);
disp(B);
fprintf('C =');
C = (1/zc)*sinh(gama*l);
disp(C);
fprintf('D =');
D = A;
disp(D);
fprintf('phi1 =');
phi1 = angle(Vr + Ir*zc);
disp(phi1);
fprintf('phi2 =');
phi2 = angle(Vr - Ir*zc);
disp(phi2);
x = l;
t = 0:0.05:0.5;
fprintf('vInci =');
vInci = (Vr + Ir*zc)*0.5*exp(gama*l);
disp(vInci);
fprintf('vRelec =');
vReflec = (Vr - Ir*zc)*0.5*exp(gama*l*(-1));
disp(vReflec);
x = 0:0.01:l;
vIncix = (Vr + Ir*zc)*0.5*exp(gama*x);
vReflecx = (Vr - Ir*zc)*0.5*exp(gama*x*(-1));
figure
plot(x, abs(vIncix),'DisplayName','Incident wave');
hold on;
plot(x, abs(vReflecx), 'DisplayName','Reflected wave');
xlabel("Distance(m)");
ylabel("Voltage(V)");
axis tight;
hold off;
legend('Location', 'southeast');
x = l;
vIncident = sqrt(2)*abs((Vr + Ir*zc))*0.5*exp(alpha*x)*cos(w*t - beta*x + phi1);
vReflected = sqrt(2)*abs((Vr - Ir*zc))*0.5*exp(alpha*x*(-1))*cos(w*t - beta*x + phi2);
figure
plot(t, vIncident,'DisplayName','Incident wave');
hold on;
plot(t, vReflected, 'DisplayName','Reflected wave');
xlabel("Distance(m)");
ylabel("Voltage(V)");
axis tight;
hold off;
legend('Location', 'southeast');
