clear ;
R1 = 25;
R2 = 20;
L = 0.5;
V = 5;
C = 10^(-5);
tau = L/(R1 + R2);
t = 0:tau/4:5*tau;
VR1inf = V*(R1)/(R1+R2);
VR2inf = V*(R2)/(R1+R2);
VLinf = 0;
VR1zr = 0;
VR2zr = 0;
VLzr = V;
VR1 = VR1inf + (VR1zr - VR1inf)*exp(-t/tau);
VR2 = VR2inf + (VR2zr - VR2inf)*exp(-t/tau);
VL = VLinf + (VLzr - VLinf)*exp(-t/tau);
iLinf = V/(R1 + R2);
iLzr = 0;
iL = iLinf + (iLzr - iLinf)*exp(-t/tau);
figure;
subtitle("Switch in Position-1");
subplot(2,2,1);
plot(t, VR1);
axis tight;
xlabel('time(s)');
ylabel('VR1(V)');
subplot(2,2,2);
plot(t, VR2);
axis tight;
xlabel('time(s)');
ylabel('VR2(V)');
subplot(2,2,3);
plot(t, VL);
axis tight;
xlabel('time(s)');
ylabel('VL(V)');
subplot(2,2,4);
plot(t, iL);
axis tight;
xlabel('time(s)');
ylabel('Current(A)');
axis("tight");
%Switch in Position-2
VLzr2 = -VLinf;
iLzr2 = iLinf;
iLinf2 = 0;
tau1 = L/R2;
t = 0:tau1/4:5*tau1;
i2 = iLinf2 + (iLzr2 - iLinf2)*exp(-t/tau1);
VR2_2 = i2*R2;
VL2 = -VR2_2;
figure;
subtitle("Switch in Position-2");
subplot(3,1,1);
plot(t, VR2_2);
axis tight;
xlabel('time(s)');
ylabel('VR2(V)');
subplot(3,1,2);
plot(t, VL2);
axis tight;
xlabel('time(s)');
ylabel('VL2(V)');
subplot(3,1,3);
plot(t, i2);
axis tight;
xlabel('time(s)');
ylabel('I2(A)');
axis("tight");
%Capacitor
tau = C*(R1 + R2);
t = 0:tau/4:5*tau;
iCzr = V/(R1 + R2);
iCinf = 0;
VCzr = 0;
VCinf = V;
VR1zr = V*R1/(R1+R2);
VR2zr = V*R2/(R1+R2);
VR1inf = 0;
VR2inf = 0;
VC = VCinf + (VCzr - VCinf)*exp(-t/tau);
iC = iCinf + (iCzr - iCinf)*exp(-t/tau);
VR1 = VR1inf + (VR1zr - VR1inf)*exp(-t/tau);
VR2 = VR2inf + (VR2zr - VR2inf)*exp(-t/tau);
figure;
subtitle("Switch in Position-1, Capacitor Connected");
subplot(2,2,1);
plot(t, VR1);
axis tight;
xlabel('time(s)');
ylabel('VR1(V)');
subplot(2,2,2);
plot(t, VR2);
axis tight;
xlabel('time(s)');
ylabel('VR2(V)');
subplot(2,2,3);
plot(t, VC);
axis tight;
xlabel('time(s)');
ylabel('VC(V)');
subplot(2,2,4);
plot(t, iC);
axis tight;
xlabel('time(s)');
ylabel('Current(A)');
axis("tight");
VCzr2 = VCinf;
VCinf2 = 0;
iCzr2 = 0;
iCinf2 = VCzr2/R2;
tau1 = C*R2;
t = 0:tau1/4:5*tau1;
iC2 = iCinf2 + (iCzr2 - iCinf2)*exp(-t/tau1);
VR2_2 = iC2*R2;
VC2 = VCinf2 + (VCzr2 - VCinf2)*exp(-t/tau1);
figure;
subtitle("Switch in Position-2, Capacitor connected");
subplot(3,1,1);
plot(t, VR2_2);
axis tight;
xlabel('time(s)');
ylabel('VR2(V)');
subplot(3,1,2);
plot(t, VC2);
axis tight;
xlabel('time(s)');
ylabel('VC(V)');
subplot(3,1,3);
plot(t, iC2);
axis tight;
xlabel('time(s)');
ylabel('I2(A)');
axis("tight");