clear;
%Nominal π
z = 0.1 + (1i*0.4);
y = 1i*3*10^(-6);
l = 250;
f = 50;
fprintf('Z =');
Z = z*l;
disp(Z);
fprintf('Y =');
Y = y*l;
disp(Y);
A = 1+((Y*Z)/2);
B = Z;
C = Y*(1+(Y*Z/4));
D = A;
disp("Long Transmission Line - Nominal-π");
fprintf('A = ');
disp(A);
fprintf('B = ');
disp(B);
fprintf('C = ');
disp(C);
fprintf('D = ');
disp(D);
%Equivalent π
fprintf('Zc = ');
zc = sqrt(z/y);
disp(zc);
fprintf('gama = ');
gama = sqrt(y*z);
disp(gama);
fprintf('Z1 = ');
Z1 = Z*sinh(gama*l)/(gama*l);
disp(Z1);
fprintf('Y1 = ');
Y1 = Y*(tanh(gama*l*0.5))/(gama*l*0.5);
disp(Y1);
A1 = 1+((Y1*Z1)/2);
B1 = Z1;
C1 = Y1*(1+(Y1*Z1/4));
D1 = A1;
disp("Long Transmission Line - Equivalent-π");
fprintf('A1 = ');
disp(A1);
fprintf('B1 = ');
disp(B1);
fprintf('C1 = ');
disp(C1);
fprintf('D1 = ');
disp(D1);
